WalletConnect WrongNetwork
Frankencoin-ZCHF/frankencoin-dapp pull request #35
Opened 2024-05-07 14:30 UTC by samclassix

based on PR#32 
https://github.com/Frankencoin-ZCHF/frankencoin-dapp/pull/32

- fixes not connected to ethereum mainnet
- opens WalletConnet (network view) to select accepted networks
- shows WalletConnect connected chain
- disables WalletConnect "Change Network Button" when connected to ethereum mainnet

Tested with MetaMask. Ok.
--> MetaMask pops open with "Allow this site to switch the network?"

2024-05-10 07:22 UTC, TaprootFreak commented
Great to see!

2024-05-10 07:23 UTC, TaprootFreak submitted a review, later dismissed

2024-05-11 07:22 UTC, samclassix commented
> Great to see!

Perfect. 

[Show NetworkButton if not ETH Mainnet](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/pull/35/commits/3e5980db5abe41f4fed720bbe3c5720cc79ef915)

This should be all, correct?

2024-05-19 14:08 UTC, luziusmeisser requested changes
As discussed, we want to switch to a new model where we have app.frankencoin.com that always connects to mainnet and devapp.frankencoin.com that can connect to Sepolia or Mainnet and that lives on the dev branch.

I suggest the following behavior (not sure if possible):
- If wallet is connected to unsupported chain, disconnect wallet silently
- If user tries to interact with the blockchain while not connected, prompt for connection

2024-05-25 06:47 UTC, closed without merging